### ISSUE TITLE
Entity blocking

### ISSUE THREAD

**Issue by AshiroKun** [Mr-EmPee/MysticalBarriers#14]
Can you add an option to block entities such as mobs from going through?

**Comment by Mr-EmPee** [comment]
Sure, I will add this feature on the next update

**Comment by AshiroKun** [comment]
thank you <3

**Comment by Mr-EmPee** [comment]
I reflected on the problem, and I'm gonna make it configurable for each barrier (By default disabled).

The solutions are:
 - Periodically checking the entities inside chunks that contain a barrier.
 - Intercepting packets
 - Listening to the entity move event provided by paper (Drop of spigot support)

I think that I will proceed the packet based solution given that I'm already depending on ProtocolLib. 
If I encounter any problem I will drop support for spigot given that the plugin stats shows that currently the 90%+ of servers using MysticalBarriers are on newer paper based fork.

**Comment by Mr-EmPee** [comment]
I'm doing a complete rewrite of the plugin, so this issue is on hold (I haven't forgotten about this issue)

**Comment by Mr-EmPee** [comment]
Implemented in b2c2ab2cff02cd78f830a27a997a323665b46d9f next release will have the feature
